"""Hold today's ldm/ to the reference values in verify/golden/.

The golden files were dumped once by verify/export_golden.py and committed. They
are the fixed point that the C, Java and Rust checks are all measured against,
so the one thing that would quietly invalidate all three is ldm/ moving away
from them without anyone noticing.

This reads the inputs out of verify/golden/ and runs the four kernels in ldm/ on
them again. It compares values rather than files, because the files cannot be
regenerated byte for byte anywhere else: torch.randn does not give the same draw
on every CPU architecture, which the CI runner demonstrated. The inputs are on
file, so the arithmetic on top of them is the same everywhere and the outputs
are held to a tolerance.

Run: python verify/check_golden.py <root>
"""
from __future__ import annotations

import sys
from pathlib import Path

import torch

ROOT = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ldm.diffusion import Diffusion, cosine_schedule
from ldm.metrics import _frechet, sliced_w2

GOLDEN = ROOT / "verify" / "golden"
T = 400
NFE = 50


def load(name: str, dtype=torch.float32) -> torch.Tensor:
    """The input files hold float32 at 9 significant digits, which round trips.

    The two reference values are float64 and are read as float64: loading them
    as float32 is worth 2e-7 on the Frechet distance, which is a hundred times
    the disagreement being looked for.
    """
    rows = [[float(v) for v in line.split()]
            for line in (GOLDEN / name).read_text().splitlines()
            if line.strip() and not line.startswith("#")]
    return torch.tensor(rows, dtype=dtype)


def eps_model(x, t):
    """The same closed form stand in for the UNet that the exporter used."""
    return torch.tanh(0.8 * x + 0.002 * t.view(-1, 1, 1, 1).float())


def report(name: str, delta: float, tol: float, detail: str) -> bool:
    ok = delta <= tol
    print(f"  {name:<34} {detail:<26} |d| {delta:.2e}  tol {tol:.0e}  "
          f"{'ok' if ok else 'FAIL'}")
    return ok


def main() -> int:
    print(f"torch {torch.__version__} against verify/golden/")
    ok = True

    abar = cosine_schedule(T)
    want = load("schedule.txt").flatten()
    ok &= report("cosine_schedule", (abar - want).abs().max().item(), 1e-7,
                 f"{T} alphas_cumprod")

    d = Diffusion(T)
    steps = torch.linspace(d.T - 1, 0, NFE).long()
    want_steps = load("ddim-steps.txt").flatten().long()
    ok &= report("the DDIM subsequence", (steps - want_steps).abs().max().item(), 0,
                 f"nfe={NFE}, integers")

    x_T = load("ddim-init.txt").view(4, 1, 4, 4)
    x0 = d.ddim_sample(eps_model, tuple(x_T.shape), nfe=NFE, eta=0.0, x_T=x_T)
    want_x0 = load("ddim-final.txt").view(4, 1, 4, 4)
    ok &= report("ddim_sample", (x0 - want_x0).abs().max().item(), 1e-5,
                 f"{NFE} steps on {x_T.numel()} elements")

    real = load("frechet-real.txt").double()
    fake = load("frechet-fake.txt").double()
    got = _frechet(real.mean(0), real.T.cov(), fake.mean(0), fake.T.cov())
    want_fr = load("frechet-value.txt", torch.float64).item()
    ok &= report("_frechet, the cFID kernel", abs(got - want_fr), 1e-7,
                 f"{got:.12f}")

    a = load("sw2-a.txt").view(-1, 1, 8, 8)
    b = load("sw2-b.txt").view(-1, 1, 8, 8)
    dirs = load("sw2-dirs.txt")
    got = sliced_w2(a, b, dirs=dirs)
    want_sw = load("sw2-value.txt", torch.float64).item()
    ok &= report("sliced_w2", abs(got - want_sw), 1e-7, f"{got:.12f}")

    if not ok:
        print("\nldm/ no longer produces the committed reference values")
        return 1
    print("\nldm/ still lands on every value in verify/golden/")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
